import { defineConfig } from "oxlint";

export default defineConfig({
    plugins: ["typescript", "unicorn", "import", "promise", "node"],
    env: {
        node: true,
    },
    categories: {
        correctness: "error",
        suspicious: "error",
        pedantic: "error",
        perf: "warn",
        style: "off",
    },
    rules: {
        "no-console": "warn",
        "no-debugger": "error",
        eqeqeq: "error",
        "no-var": "error",
        "prefer-const": "error",
        "object-shorthand": "error",
        curly: "error",
        "no-duplicate-imports": "error",
        "no-useless-constructor": "error",
        "no-unreachable": "error",
        "no-constant-condition": "error",
        "no-self-compare": "error",
        "no-template-curly-in-string": "error",
        "no-unneeded-ternary": "error",
        "typescript/no-explicit-any": "error",
        "typescript/no-non-null-assertion": "error",
        "typescript/no-namespace": "error",
        "typescript/consistent-type-imports": "error",
        "typescript/ban-ts-comment": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/no-array-reduce": "off",
        "unicorn/no-process-exit": "error",
        "unicorn/no-array-sort": "off",
        "unicorn/prefer-event-target": "off",
        "no-inline-comments": "off",
        "max-lines": "off",
        "max-lines-per-function": "off",
        "import/no-cycle": "error",
        "import/no-duplicates": "error",
        "import/no-self-import": "error",
        "promise/no-return-wrap": "error",
        "promise/no-nesting": "warn",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/no-unnecessary-type-assertion": "off",
        "max-classes-per-file": "off",
        "prefer-readonly-parameter-types": "off",
    },
    ignorePatterns: ["dist", "coverage", "node_modules", "*.config.js"],
});
