/**
 * TLS handshake protocol (RFC 8446 §4, RFC 5246 §7).
 *
 * Builds and parses the handshake messages and drives the handshake state machine.
 * Cryptographic operations (key generation, signing, verification) are delegated
 * to @browsercore/crypto; this module owns message layout and state transitions.
 */

import { crypto } from "@browsercore/crypto";
import type {
    CipherSuite,
    ClientHelloConfig,
    KeyPair,
    NamedGroup,
    ProtocolVersion,
    SignatureScheme,
} from "../types.js";
import { TlsHandshakeError } from "../errors.js";
import { assertNever } from "../utils.js";
import {
    ExtensionType,
    findExtension,
    namedGroupToWire,
    parseExtensions,
    signatureSchemeToWire,
} from "../extensions/extensions.js";
import { assertCipherSuiteOffered, assertVersionSupported } from "../crypto/keySchedule.js";

/** TLS handshake message types, per RFC 8446 §4. */
export const HandshakeType = {
    HELLO_REQUEST: 0,
    CLIENT_HELLO: 1,
    SERVER_HELLO: 2,
    NEW_SESSION_TICKET: 4,
    END_OF_EARLY_DATA: 5,
    ENCRYPTED_EXTENSIONS: 8,
    CERTIFICATE: 11,
    SERVER_KEY_EXCHANGE: 12,
    CERTIFICATE_REQUEST: 13,
    SERVER_HELLO_DONE: 14,
    CERTIFICATE_VERIFY: 15,
    CLIENT_KEY_EXCHANGE: 16,
    FINISHED: 20,
    KEY_UPDATE: 24,
    MESSAGE_HASH: 254,
} as const;

/** Union of valid handshake message-type values. */
export type HandshakeType = (typeof HandshakeType)[keyof typeof HandshakeType];

/** A parsed ClientHello (sent by the client, parsed when acting as server — not used client-side but typed for completeness). */
export interface ClientHello {
    readonly protocolVersion: number;
    readonly random: Uint8Array;
    readonly sessionId: Uint8Array;
    readonly cipherSuites: readonly number[];
    readonly compressionMethods: readonly number[];
    readonly extensions: Uint8Array;
}

/** A parsed ServerHello — the first handshake message the server sends. */
export interface ServerHello {
    /**
     * Legacy protocol version (always 0x0303 for TLS 1.3, for middlebox
     * compatibility). The real negotiated version is {@link selectedVersion}.
     */
    readonly protocolVersion: number;
    readonly random: Uint8Array;
    readonly sessionId: Uint8Array;
    readonly cipherSuite: CipherSuite;
    readonly compressionMethod: number;
    /**
     * The protocol version the server actually negotiated, extracted from the
     * supported_versions extension. This is the authoritative version.
     */
    readonly selectedVersion: ProtocolVersion;
    readonly extensions: Uint8Array;
}

/** Phases of the client-side handshake state machine. */
export type HandshakePhase =
    | { readonly phase: "start" }
    | { readonly phase: "client_hello_sent" }
    | { readonly phase: "server_hello_received"; readonly serverHello: ServerHello }
    | { readonly phase: "encrypted_extensions_received" }
    | { readonly phase: "certificate_received" }
    | { readonly phase: "certificate_verify_received" }
    | { readonly phase: "finished_received" }
    | { readonly phase: "complete" };

/** TLS 1.2 wire version used as legacy_version in TLS 1.3 records/handshakes. */
const TLS_1_2_WIRE_VERSION = 0x0303;

/** Cipher suite IANA wire values (subset used by TLS 1.3). */
function cipherSuiteToWire(suite: CipherSuite): number {
    switch (suite) {
        case "TLS_AES_128_GCM_SHA256":
            return 0x1301;
        case "TLS_AES_256_GCM_SHA384":
            return 0x1302;
        case "TLS_CHACHA20_POLY1305_SHA256":
            return 0x1303;
        case "TLS_AES_128_CCM_SHA256":
            return 0x1304;
    }
}

/** Invert {@link cipherSuiteToWire}; throws on unknown values. */
function wireToCipherSuite(wire: number): CipherSuite {
    switch (wire) {
        case 0x1301:
            return "TLS_AES_128_GCM_SHA256";
        case 0x1302:
            return "TLS_AES_256_GCM_SHA384";
        case 0x1303:
            return "TLS_CHACHA20_POLY1305_SHA256";
        case 0x1304:
            return "TLS_AES_128_CCM_SHA256";
        default:
            throw new TlsHandshakeError("server_hello", {
                cause: new Error(`unsupported cipher suite wire value: 0x${wire.toString(16)}`),
            });
    }
}

/**
 * Build a ClientHello handshake message from the given config.
 *
 * Serializes the full handshake message (header + body) with extensions for SNI,
 * supported_versions, key_share, signature_algorithms, and (optionally) ALPN.
 * The (EC)DHE public keys come from `keyPairs` (already generated by the caller
 * via @browsercore/crypto).
 */
export function buildClientHello(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
): Uint8Array {
    const random = crypto.randomBytes(32);
    const sessionId = new Uint8Array(0);
    const compressionMethods = new Uint8Array([0x00]);

    const extensions = buildClientHelloExtensions(config, keyPairs);

    // Body length: version(2) + random(32) + session_id_len(1) + session_id +
    //   cipher_suites_len(2) + cipher_suites + compression_len(1) + compression +
    //   extensions_len(2) + extensions.
    const cipherSuitesBytes = new Uint8Array(config.cipherSuites.length * 2);
    for (let i = 0; i < config.cipherSuites.length; i++) {
        const wire = cipherSuiteToWire(config.cipherSuites[i]!);
        cipherSuitesBytes[i * 2] = (wire >> 8) & 0xff;
        cipherSuitesBytes[i * 2 + 1] = wire & 0xff;
    }

    const bodyLen =
        2 + random.length + 1 + sessionId.length +
        2 + cipherSuitesBytes.length +
        1 + compressionMethods.length +
        2 + extensions.length;

    // Handshake header: msg_type(1) + length(24-bit) + body.
    const message = new Uint8Array(1 + 3 + bodyLen);
    let o = 0;
    message[o++] = HandshakeType.CLIENT_HELLO;
    message[o++] = (bodyLen >> 16) & 0xff;
    message[o++] = (bodyLen >> 8) & 0xff;
    message[o++] = bodyLen & 0xff;

    // legacy_version = 0x0303 (TLS 1.2 for middlebox compatibility).
    message[o++] = (TLS_1_2_WIRE_VERSION >> 8) & 0xff;
    message[o++] = TLS_1_2_WIRE_VERSION & 0xff;
    message.set(random, o);
    o += random.length;

    // Session ID (length-prefixed; empty for TLS 1.3).
    message[o++] = sessionId.length & 0xff;
    message.set(sessionId, o);
    o += sessionId.length;

    // Cipher suites (length-prefixed).
    message[o++] = (cipherSuitesBytes.length >> 8) & 0xff;
    message[o++] = cipherSuitesBytes.length & 0xff;
    message.set(cipherSuitesBytes, o);
    o += cipherSuitesBytes.length;

    // Compression methods (length-prefixed; single null).
    message[o++] = compressionMethods.length & 0xff;
    message.set(compressionMethods, o);
    o += compressionMethods.length;

    // Extensions (length-prefixed).
    message[o++] = (extensions.length >> 8) & 0xff;
    message[o++] = extensions.length & 0xff;
    message.set(extensions, o);

    return message;
}

/**
 * Serialize the extensions block for a ClientHello. Each extension is
 * type(2) || data_len(2) || data, all under a single length-prefix.
 */
function buildClientHelloExtensions(config: ClientHelloConfig, keyPairs: readonly KeyPair[]): Uint8Array {
    const parts: readonly Uint8Array[] = [
        wrapExtension(ExtensionType.SERVER_NAME, encodeServerNameList(config.serverName)),
        wrapExtension(ExtensionType.SUPPORTED_VERSIONS, encodeSupportedVersionsClient(config.supportedVersions)),
        wrapExtension(ExtensionType.KEY_SHARE, encodeKeyShareClient(keyPairs)),
        wrapExtension(ExtensionType.SIGNATURE_ALGORITHMS, encodeSignatureAlgorithms(config.signatureAlgorithms)),
        ...(config.alpnProtocols !== undefined && config.alpnProtocols.length > 0
            ? [wrapExtension(ExtensionType.APPLICATION_LAYER_PROTOCOL_NEGOTIATION, encodeAlpn(config.alpnProtocols))]
            : []),
    ];

    let total = 0;
    for (const p of parts) {
        total += p.length;
    }
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}

/** Wrap an extension body with its type + length prefix. */
function wrapExtension(type: ExtensionType, data: Uint8Array): Uint8Array {
    const out = new Uint8Array(2 + 2 + data.length);
    out[0] = (type >> 8) & 0xff;
    out[1] = type & 0xff;
    out[2] = (data.length >> 8) & 0xff;
    out[3] = data.length & 0xff;
    out.set(data, 4);
    return out;
}

/** Encode the SNI server_name_list body (RFC 6066 §3). */
function encodeServerNameList(serverName: string): Uint8Array {
    const nameBytes = new TextEncoder().encode(serverName);
    if (nameBytes.length > 0xffff) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error("SNI server_name exceeds 65535 bytes"),
        });
    }
    // server_name_list: length(2) + entries. Each entry: type(1)=0 + length(2) + name.
    const entry = new Uint8Array(1 + 2 + nameBytes.length);
    entry[0] = 0; // host_name
    entry[1] = (nameBytes.length >> 8) & 0xff;
    entry[2] = nameBytes.length & 0xff;
    entry.set(nameBytes, 3);

    const out = new Uint8Array(2 + entry.length);
    out[0] = (entry.length >> 8) & 0xff;
    out[1] = entry.length & 0xff;
    out.set(entry, 2);
    return out;
}

/** Encode the supported_versions extension body for the client (RFC 8446 §4.2.1). */
function encodeSupportedVersionsClient(versions: readonly ProtocolVersion[]): Uint8Array {
    const out = new Uint8Array(1 + versions.length * 2);
    out[0] = (versions.length * 2) & 0xff;
    for (let i = 0; i < versions.length; i++) {
        const wire = versions[i]!.wire;
        out[1 + i * 2] = (wire >> 8) & 0xff;
        out[1 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Encode the key_share extension body for the client (RFC 8446 §4.2.8). */
function encodeKeyShareClient(keyPairs: readonly KeyPair[]): Uint8Array {
    // client_shares: length(2) + entries. Each: group(2) + len(2) + key_exchange.
    let entriesLen = 0;
    for (const kp of keyPairs) {
        entriesLen += 2 + 2 + kp.publicKey.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const kp of keyPairs) {
        const groupWire = namedGroupToWire(kp.algorithm as NamedGroup);
        out[o++] = (groupWire >> 8) & 0xff;
        out[o++] = groupWire & 0xff;
        out[o++] = (kp.publicKey.length >> 8) & 0xff;
        out[o++] = kp.publicKey.length & 0xff;
        out.set(kp.publicKey, o);
        o += kp.publicKey.length;
    }
    return out;
}

/** Encode the signature_algorithms extension body (RFC 8446 §4.2.3). */
function encodeSignatureAlgorithms(algorithms: readonly SignatureScheme[]): Uint8Array {
    const out = new Uint8Array(2 + algorithms.length * 2);
    out[0] = ((algorithms.length * 2) >> 8) & 0xff;
    out[1] = (algorithms.length * 2) & 0xff;
    for (let i = 0; i < algorithms.length; i++) {
        const wire = signatureSchemeToWire(algorithms[i]!);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Encode the ALPN extension body (RFC 7301). */
function encodeAlpn(protocols: readonly string[]): Uint8Array {
    let entriesLen = 0;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        if (encoded.length === 0 || encoded.length > 0xff) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`ALPN protocol must be 1..255 bytes: "${proto}"`),
            });
        }
        entriesLen += 1 + encoded.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        out[o++] = encoded.length & 0xff;
        out.set(encoded, o);
        o += encoded.length;
    }
    return out;
}

/**
 * What the client offered in its ClientHello, needed so the ServerHello can be
 * validated against it. Only the fields that {@link parseServerHello} checks are
 * required — everything else is irrelevant to ServerHello parsing.
 */
export interface ServerHelloValidation {
    /** Cipher suites the client advertised, most-preferred first. */
    readonly cipherSuites: readonly CipherSuite[];
    /** Protocol versions the client advertised via supported_versions. */
    readonly supportedVersions: readonly ProtocolVersion[];
}

/**
 * Map a 16-bit wire version to the branded {@link ProtocolVersion} from the
 * offered list. Throws if the server selected a version we did not offer.
 */
function selectVersion(wire: number, offered: readonly ProtocolVersion[]): ProtocolVersion {
    for (const version of offered) {
        if (version.wire === wire) {
            return version;
        }
    }
    throw new TlsHandshakeError("server_hello", {
        cause: new Error(`server negotiated version we did not offer: 0x${wire.toString(16)}`),
    });
}

/**
 * Parse a ServerHello from a handshake message body (without the 4-byte handshake header).
 *
 * Validates that the selected cipher suite was actually offered and that the
 * negotiated protocol version (from the supported_versions extension) is one we
 * support — failing fast makes an unacceptable negotiation unrepresentable.
 *
 * Throws {@link TlsHandshakeError} with phase "server_hello" on malformed input
 * or a failed validation.
 */
export function parseServerHello(buf: Uint8Array, offered: ServerHelloValidation): ServerHello {
    let o = 0;
    const expect = (n: number): void => {
        if (o + n > buf.length) {
            throw new TlsHandshakeError("server_hello", {
                cause: new Error(`ServerHello truncated at offset ${o} (need ${n}, have ${buf.length - o})`),
            });
        }
    };

    expect(2 + 32 + 1);
    const protocolVersion = (buf[o++]! << 8) | buf[o++]!;
    const random = buf.subarray(o, o + 32);
    o += 32;

    const sessionIdLen = buf[o++]!;
    expect(sessionIdLen);
    const sessionId = buf.subarray(o, o + sessionIdLen);
    o += sessionIdLen;

    expect(2 + 1 + 2);
    const cipherSuiteWire = (buf[o++]! << 8) | buf[o++]!;
    const cipherSuite = wireToCipherSuite(cipherSuiteWire);
    const compressionMethod = buf[o++]!;
    if (compressionMethod !== 0x00) {
        throw new TlsHandshakeError("server_hello", {
            cause: new Error(`unsupported compression method: ${compressionMethod}`),
        });
    }

    // The server MUST negotiate a cipher suite we offered.
    assertCipherSuiteOffered(cipherSuite, offered.cipherSuites);

    // Capture the offset before reading extensions_len so the slice retains the
    // 2-byte length prefix. parseExtensions (used both here for the
    // supported_versions extension and later by the key-share extraction in
    // _computeSharedSecret) requires its input to be the length-prefixed block.
    const extensionsStart = o;
    const extensionsLen = (buf[o++]! << 8) | buf[o++]!;
    expect(extensionsLen);
    const extensions = buf.subarray(extensionsStart, o + extensionsLen);

    const selectedVersion = negotiateVersion(extensions, offered.supportedVersions);

    void protocolVersion;
    return { protocolVersion, random, sessionId, cipherSuite, compressionMethod, selectedVersion, extensions };
}

/**
 * Extract the version the server negotiated from the supported_versions
 * extension (RFC 8446 §4.2.1) and validate it. The server's extension body is a
 * single uint16 — the one version it selected from our offered list.
 */
function negotiateVersion(extensionsRaw: Uint8Array, offered: readonly ProtocolVersion[]): ProtocolVersion {
    const extensions = parseExtensions(extensionsRaw);
    const sv = findExtension(extensions, ExtensionType.SUPPORTED_VERSIONS);
    if (sv === undefined) {
        throw new TlsHandshakeError("server_hello", {
            cause: new Error("ServerHello missing required supported_versions extension"),
        });
    }
    if (sv.data.length !== 2) {
        throw new TlsHandshakeError("server_hello", {
            cause: new Error(`supported_versions extension has unexpected length ${sv.data.length}`),
        });
    }
    const wire = (sv.data[0]! << 8) | sv.data[1]!;
    const selected = selectVersion(wire, offered);
    assertVersionSupported(selected);
    return selected;
}

/**
 * Transition the handshake state machine given the next received message type.
 * Returns the next phase, or throws {@link TlsHandshakeError} on an invalid
 * transition (making invalid state sequences unrepresentable).
 */
export function advanceHandshake(current: HandshakePhase, received: HandshakeType): HandshakePhase {
    switch (current.phase) {
        case "start":
            throw new TlsHandshakeError("client_hello", {
                cause: new Error("expected client_hello_sent as the first transition"),
            });
        case "client_hello_sent":
            if (received !== HandshakeType.SERVER_HELLO) {
                throw new TlsHandshakeError("server_hello", {
                    cause: new Error(`expected SERVER_HELLO after client_hello_sent, got ${received}`),
                });
            }
            // The caller must call `recordServerHello` to attach the parsed ServerHello.
            throw new TlsHandshakeError("server_hello", {
                cause: new Error(
                    "use recordServerHello(serverHello) to transition client_hello_sent -> server_hello_received",
                ),
            });
        case "server_hello_received":
            if (received !== HandshakeType.ENCRYPTED_EXTENSIONS) {
                throw new TlsHandshakeError("server_hello", {
                    cause: new Error(`expected ENCRYPTED_EXTENSIONS, got ${received}`),
                });
            }
            return { phase: "encrypted_extensions_received" };
        case "encrypted_extensions_received":
            if (received !== HandshakeType.CERTIFICATE) {
                throw new TlsHandshakeError("certificate", {
                    cause: new Error(`expected CERTIFICATE, got ${received}`),
                });
            }
            return { phase: "certificate_received" };
        case "certificate_received":
            if (received !== HandshakeType.CERTIFICATE_VERIFY) {
                throw new TlsHandshakeError("certificate", {
                    cause: new Error(`expected CERTIFICATE_VERIFY, got ${received}`),
                });
            }
            return { phase: "certificate_verify_received" };
        case "certificate_verify_received":
            if (received !== HandshakeType.FINISHED) {
                throw new TlsHandshakeError("finished", {
                    cause: new Error(`expected FINISHED, got ${received}`),
                });
            }
            return { phase: "finished_received" };
        case "finished_received":
        case "complete":
            throw new TlsHandshakeError("finished", {
                cause: new Error(`handshake already in terminal phase: ${current.phase}`),
            });
        default:
            return assertNever(current);
    }
}

/**
 * Record the parsed ServerHello and transition from "client_hello_sent" to
 * "server_hello_received". Separated from {@link advanceHandshake} because the
 * state machine needs to carry the parsed ServerHello forward.
 */
export function recordServerHello(_current: HandshakePhase, serverHello: ServerHello): HandshakePhase {
    void _current;
    return { phase: "server_hello_received", serverHello };
}

/** Mark the handshake as complete (after client Finished is sent). */
export function completeHandshake(_current: HandshakePhase): HandshakePhase {
    void _current;
    return { phase: "complete" };
}

/** True if the named group is a (EC)DHE group usable for TLS 1.3 key share. */
export function isKeyShareGroup(group: NamedGroup): boolean {
    switch (group) {
        case "secp256r1":
        case "secp384r1":
        case "x25519":
        case "x448":
            return true;
    }
}

/** True if the protocol version is TLS 1.3. */
export function isTls13(version: ProtocolVersion): boolean {
    return version.name === "TLS 1.3";
}
